### ISSUE TITLE
"virtual-jade" does not support the "extends", "include" and other key words

### ISSUE THREAD

**Issue by fengxinming** [tdumitrescu/virtual-jade#8]
Error: the "filename" option is required to use "extends" with "relative" paths 
 at Parser.resolvePath (D:\demows\koa-demo\node_modules\jade\lib\parser.js:486:13)
    at Parser.parseExtends (D:\demows\koa-demo\node_modules\jade\lib\parser.js:505:21)
    at Parser.parseExpr (D:\demows\koa-demo\node_modules\jade\lib\parser.js:221:21)
    at Parser.parse (D:\demows\koa-demo\node_modules\jade\lib\parser.js:122:25)
    at render (D:\demows\koa-demo\node_modules\virtual-jade\lib\index.js:43:25)
    at DestroyableTransform.CompileJade [as _transform] (D:\demows\koa-demo\tasks\gulp\plugins\virtual-jade.js:30:32)
    at DestroyableTransform.Transform._read (D:\demows\koa-demo\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (D:\demows\koa-demo\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (D:\demows\koa-demo\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (D:\demows\koa-demo\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:302:5)

**Comment by tdumitrescu** [comment]
Indeed, multifile features like extends and include have not yet been implemented. Pull requests welcome!

**Comment by tdumitrescu** [comment]
OK, as of v0.3.0, `include` and `extends` are supported. You must pass `filename` as an option to the `render()` function in order for the parser to find the included files, e.g.,
```javascript
render(srcString, {filename: 'myfile.jade'});
```
See https://github.com/tdumitrescu/virtual-jade/blob/d28ab9261758a1631e98585e6418caac32c8e8ac/test/test.js#L12-L14 in the test suite for a version using an absolute path for the filename option.
